### ISSUE TITLE
[BUG] Missing github repo

### ISSUE THREAD

**Issue by ForBai** [Polyfrost/OneConfig-Documentation#2]
The docs say that you you should clone(use Version Control) a github repo(https://github.com/Polyfrost/OneConfigExampleMod) but this repo does not exist.
Is there any other mod that already uses it?

**Comment by nextdayy** [comment]
Hi,
This is because that repo is on private mode still, as it is still in its very early stages.
Once it's finished enough, it will be made public (around 3-4 days hopefully)!

**Comment by ForBai** [comment]
Ok, thank you for your fast reply.

**Comment by Wyvest** [comment]
i mean it should be ready to oss in a day once i update it to the new config api

**Comment by pauliesnug** [comment]
The repo is now public :D

**Comment by ForBai** [comment]
Thank you
